---
- name: "rhsm-registration | Register system to RHSM"
  # redhat_subscription:
  #   state: present
  #   username: "{{ rhsm_user }}"
  #   password: "{{ rhsm_password }}"
  #   auto_attach: true
  shell: "ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /home/{{ rhv_vm_ssh_username }}/.ssh/id_rsa {{ rhv_vm_ssh_username }}@{{ rhv_vm_hostname }} 'sudo {{ item }}'"
  #ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes
  with_items:
    - "subscription-manager register --username={{ rhsm_user }} --password={{ rhsm_password }}"
    - "subscription-manager attach"
    - "subscription-manager repos --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-optional-rpms --enable=rhel-7-server-supplementary-rpms"
       # --enable=rhel-7-server-rpms is set by default
    - "yum check-update"
#
## - shell: "ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null {{ rhv_vm_hostname }} {{ item.command }}"
#
#- name: "rhsm-registration | Update system"
#  yum:
#    name: '*'
#    state: latest

