---
- hosts: localhost
  roles:
   - { role: vm_rhsm_unregistration }
   - { role: rhv_vm_delete }
   - { role: vm_dns_entry_removal }

  vars_files:
    - ../../vars/vms/vars.yml
    # - ../../environments/rhev-m/group_vars/all/vault/vault.yml
