---
- name: "Unregister system from RHSM"

  shell: "ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -o ControlPersist=60s {{ rhv_vm_ssh_username }}@{{ rhv_vm_hostname }} 'sudo {{ item }}'"
  with_items:
    - "subscription-manager unsubscribe --all"
    - "subscription-manager unregister"