---
- name: "Create RHV VM"
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: rhv_vm_create }
    - { role: vm_dns_entry }
    - { role: vm_rhsm_registration }
    - { role: vm_system_patch }

  vars_files:
    - ../../vars/vms/vars.yml
    # - ../../environments/rhev-m/group_vars/all/vault/vault.yml
