---
- name: "Create RHV VM"
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: rhv_vm }
    - { role: dns_entry }
    - { role: rhsm-registration }

  vars_files:
    - ../../vars/rhv_vm/vars.yml
    # - ../../environments/rhev-m/group_vars/all/vault/vault.yml
