- set_fact:
    host: "{{ rhv_vm_hostname.split('.')[0] }}"

- name: "Remove {{ host }} A record"
  ipa_dnsrecord:
    name: "{{ host }}"
    zone_name: "{{ '.'.join(rhv_vm_hostname.split('.')[-2:]) }}" # Get the domain from the FQDN
    record_type: A
    record_value: "{{ rhv_vm_public_ip }}"
    ipa_host: "{{ ipa_hostname }}"
    ipa_user: "{{ ipa_username }}"
    ipa_pass: "{{ ipa_password }}"
    validate_certs: no
    state: absent

